# ==============================================================================
# Rebung Pintar — Konfigurasi Node 3: Mosquitto MQTT Broker
# Port 1883: MQTT TCP untuk ESP32 Hardware & Laravel Backend Subscriber
# Port 9001: MQTT WebSockets untuk Dashboard Web & Flutter Mobile App
# ==============================================================================

# 1. Listener TCP Biasa (ESP32 & Laravel CLI Worker)
listener 1883 0.0.0.0
protocol mqtt

# 2. Listener WebSockets (Mobile App / Web Dashboard)
listener 9001 0.0.0.0
protocol websockets

# Keamanan & Autentikasi
allow_anonymous true

# Persistensi Data
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
